import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { CleanableItem, ScanResult } from '../types';
import { getPathSize, pathExists } from './fsUtils';

export async function scanPhotosJunk(): Promise<ScanResult> {
  const home = os.homedir();
  const items: CleanableItem[] = [];

  const targets = [
    {
      id: 'photos_cache',
      name: 'Photos App Render & Derivative Cache',
      category: 'photos',
      path: path.join(home, 'Pictures/Photos Library.photoslibrary/resources/derivatives'),
      description: 'Pre-rendered image sizes and thumbnail cache generated by Apple Photos. Photos regenerates them as needed.',
      safeToDelete: true,
    },
    {
      id: 'photos_renders',
      name: 'Photos Face Detection & Analysis Cache',
      category: 'photos',
      path: path.join(home, 'Pictures/Photos Library.photoslibrary/resources/renders'),
      description: 'Cached filter renders and visual analysis files.',
      safeToDelete: true,
    },
    {
      id: 'spotify_media_cache',
      name: 'Spotify Offline Streaming Cache',
      category: 'photos',
      path: path.join(home, 'Library/Caches/com.spotify.client/Data'),
      description: 'Audio song cache stored locally by Spotify.',
      safeToDelete: true,
    },
    {
      id: 'music_cache',
      name: 'Apple Music Artwork & Streaming Cache',
      category: 'photos',
      path: path.join(home, 'Library/Caches/com.apple.Music'),
      description: 'High-res album art and temporary streaming buffers.',
      safeToDelete: true,
    },
    {
      id: 'imovie_cache',
      name: 'iMovie & Video Render Caches',
      category: 'photos',
      path: path.join(home, 'Library/Caches/com.apple.iMovieApp'),
      description: 'Pre-rendered video frames and background export scratch files.',
      safeToDelete: true,
    },
  ];

  for (const target of targets) {
    if (await pathExists(target.path)) {
      const size = await getPathSize(target.path);
      if (size > 1024 * 100) {
        items.push({
          id: target.id,
          name: target.name,
          category: 'photos',
          path: target.path,
          size,
          selected: true,
          safeToDelete: target.safeToDelete,
          description: target.description,
        });
      }
    }
  }

  // Scan screenshots in Desktop / Pictures older than 14 days
  const desktopPath = path.join(home, 'Desktop');
  if (await pathExists(desktopPath)) {
    try {
      const files = await fs.promises.readdir(desktopPath, { withFileTypes: true });
      const screenshotItems: CleanableItem[] = [];
      let totalScreenshotSize = 0;

      for (const f of files) {
        if (f.isFile() && (f.name.startsWith('Screenshot') || f.name.startsWith('Screen Shot') || f.name.startsWith('Capture d’écran'))) {
          const filePath = path.join(desktopPath, f.name);
          const stat = await fs.promises.stat(filePath);
          totalScreenshotSize += stat.size;
          screenshotItems.push({
            id: `screenshot_${f.name}`,
            name: f.name,
            category: 'photos',
            path: filePath,
            size: stat.size,
            selected: false, // unselected by default for safety
            safeToDelete: true,
            description: `Desktop Screenshot (${new Date(stat.mtimeMs).toLocaleDateString()})`,
            lastModified: stat.mtimeMs,
          });
        }
      }

      if (screenshotItems.length > 0) {
        items.push({
          id: 'desktop_screenshots',
          name: 'Old Desktop Screenshots',
          category: 'photos',
          path: desktopPath,
          size: totalScreenshotSize,
          selected: false,
          safeToDelete: true,
          description: 'Screenshots cluttering your Desktop. Review and clean up.',
          itemCount: screenshotItems.length,
          subItems: screenshotItems,
        });
      }
    } catch {
      // Ignore
    }
  }

  const totalSize = items.reduce((acc, curr) => acc + curr.size, 0);
  const itemCount = items.reduce((acc, curr) => acc + (curr.subItems?.length || 1), 0);

  return {
    category: 'photos',
    title: 'Photos & Media Caches',
    totalSize,
    itemCount,
    items,
    scannedAt: Date.now(),
  };
}
