import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { CleanableItem, ScanResult } from '../types';
import { expandHome, getPathSize, pathExists } from './fsUtils';

export async function scanSystemJunk(): Promise<ScanResult> {
  const home = os.homedir();
  const items: CleanableItem[] = [];

  const targets = [
    {
      id: 'user_caches',
      name: 'User Application Caches',
      category: 'system',
      path: path.join(home, 'Library/Caches'),
      description: 'Temporary cached data created by everyday applications to speed up performance. Safe to remove.',
      safeToDelete: true,
      scanChildren: true,
    },
    {
      id: 'user_logs',
      name: 'User System Logs',
      category: 'system',
      path: path.join(home, 'Library/Logs'),
      description: 'Activity logs, diagnostic traces, and crash history generated by macOS user apps.',
      safeToDelete: true,
      scanChildren: true,
    },
    {
      id: 'diagnostic_reports',
      name: 'Crash & Diagnostic Reports',
      category: 'system',
      path: path.join(home, 'Library/Logs/DiagnosticReports'),
      description: 'Crash logs and diagnostic dumps from frozen or terminated processes.',
      safeToDelete: true,
      scanChildren: false,
    },
    {
      id: 'system_trash',
      name: 'macOS Trash Bin',
      category: 'system',
      path: path.join(home, '.Trash'),
      description: 'Files and folders waiting in your macOS Trash to be permanently purged.',
      safeToDelete: true,
      scanChildren: true,
    },
    {
      id: 'saved_app_states',
      name: 'Saved Application State',
      category: 'system',
      path: path.join(home, 'Library/Saved Application State'),
      description: 'Snapshots of previous app window states. Deleting these forces fresh starts and clears stalled caches.',
      safeToDelete: true,
      scanChildren: true,
    },
    {
      id: 'quicklook_cache',
      name: 'QuickLook Thumbnail Cache',
      category: 'system',
      path: path.join(home, 'Library/Caches/com.apple.QuickLook.thumbnailcache'),
      description: 'Finder preview thumbnails for quick file previewing.',
      safeToDelete: true,
      scanChildren: false,
    },
    {
      id: 'system_caches',
      name: 'System-wide Caches',
      category: 'system',
      path: '/Library/Caches',
      description: 'System-level application and framework cache files.',
      safeToDelete: true,
      scanChildren: true,
    },
    {
      id: 'system_logs',
      name: 'System-wide Logs',
      category: 'system',
      path: '/Library/Logs',
      description: 'Daemon, system services, and background daemon log files.',
      safeToDelete: true,
      scanChildren: true,
    },
  ];

  for (const target of targets) {
    if (!(await pathExists(target.path))) continue;

    if (target.scanChildren) {
      try {
        const entries = await fs.promises.readdir(target.path, { withFileTypes: true });
        const subItems: CleanableItem[] = [];
        let groupTotalSize = 0;

        for (const entry of entries) {
          if (entry.name.startsWith('.')) continue; // ignore hidden system markers
          const entryPath = path.join(target.path, entry.name);
          const size = await getPathSize(entryPath);
          if (size > 1024 * 50) { // filter out zero or tiny items < 50KB to keep list clean
            groupTotalSize += size;
            subItems.push({
              id: `${target.id}_${entry.name}`,
              name: entry.name,
              category: 'system',
              path: entryPath,
              size,
              selected: true,
              safeToDelete: target.safeToDelete,
              description: `${entry.isDirectory() ? 'Folder' : 'File'} in ${target.name}`,
            });
          }
        }

        // Sort largest subItems first
        subItems.sort((a, b) => b.size - a.size);

        if (subItems.length > 0) {
          items.push({
            id: target.id,
            name: target.name,
            category: 'system',
            path: target.path,
            size: groupTotalSize,
            selected: true,
            safeToDelete: target.safeToDelete,
            description: target.description,
            itemCount: subItems.length,
            subItems,
          });
        }
      } catch {
        // Fallback to single item if directory read error
      }
    } else {
      const size = await getPathSize(target.path);
      if (size > 1024 * 10) {
        items.push({
          id: target.id,
          name: target.name,
          category: 'system',
          path: target.path,
          size,
          selected: true,
          safeToDelete: target.safeToDelete,
          description: target.description,
        });
      }
    }
  }

  const totalSize = items.reduce((acc, curr) => acc + curr.size, 0);
  const itemCount = items.reduce((acc, curr) => acc + (curr.subItems?.length || 1), 0);

  return {
    category: 'system',
    title: 'System Junk & Caches',
    totalSize,
    itemCount,
    items,
    scannedAt: Date.now(),
  };
}
